### ISSUE TITLE
escape | in mods metadata extracted to the workbench input csv

### ISSUE THREAD

**Issue by ilovan** [cwrc/islandora-etl#4]
`Warning: CSV field "field_description" in record with ID reed:d91d1a0e-17d3-4ebe-8dc1-5d50c574ff3f contains more values than the number allowed for that field (1). Workbench will add only the first value.`

**Comment by jefferya** [comment]
changed the subdelimiter to `^|.|^` - <https://github.com/cwrc/islandora-etl/blob/44d160b8f1ee027f36be4a116e9feed33894f75c/transform_to_workbench/islandora7_to_workbench_utils.xquery#L18> . 

This must match the Islandora Workbench config 
<https://github.com/cwrc/islandora-etl/blob/a35972954501c814fe91da9b67060f86a3f86fef/config/workbench_config_sample.yaml#L9>
